from django.urls import path
from .views import *

urlpatterns = [
    path('', home, name='home'),
    path('clothes/', clothes, name='clothes'),
    path('clothes/<pk>/', clothes_detail, name='clothes_detail'),
    path('clothes/<pk>/delete/', clothes_delete, name='clothes_delete'),
    path('clothes/<pk>/update/', clothes_update, name='clothes_update'),
    path('electronics/', electronics, name='electronics'),
    path('electronics/<pk>/', elec_detail, name='elec_detail'),
    path('electronics/<pk>/delete/', elec_delete, name='elec_delete'),
    path('electronics/<pk>/update/', elec_update, name='elec_update'),
    path('furnitures/', furnitures, name='furnitures'),
    path('furnitures/<pk>/', fur_detail, name='fur_detail'),
    path('furnitures/<pk>/delete/', fur_delete, name='fur_delete'),
    path('furnitures/<pk>/update/', fur_update, name='elec_update'),
    path('sport/', sports, name='sports'),
    path('sport/<pk>/', sports_detail, name='sports_detail'),
    path('sport/<pk>/delete/', sports_delete, name='sport_delete'),
    path('sport/<pk>/update/', sports_update, name='sport_update'),
    path('household/', households, name='household'),
    path('household/<pk>/', house_detail, name='house_detail'),
    path('household/<pk>/delete/', house_delete, name='house_delete'),
    path('household/<pk>/update/', house_update, name='house_update'),
    path('about/', about, name='about'),
    path('cart/', cart, name='cart'),
    path('create/', create, name='create'),
    path('create2/', create2, name='create2'),
    path('create3/', create3, name='create3'),
    path('create4/', create4, name='create4'),
    path('create5/', create5, name='create5'),
]